version: "3"
services:
  vet:
    build:
      context: .
    ports:
      - "8002:8001"
    depends_on:
      - db
    volumes:
      - .:/app
    restart: always
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: hero
      POSTGRES_PASSWORD: hero
      POSTGRES_DB: munchies
    ports:
      - "5433:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    restart: always

volumes:
  postgres_data:
