# Generated by Django 4.2.4 on 2023-08-18 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_cover_picture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address_line_1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='address_line_2',
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'clinic'), (2, 'customer')], null=True),
        ),
    ]
